theme: jekyll-theme-leap-day
# title: ['李鸿敏(Li Hongmin)']
description: [Welcome to Li Hongmin' homepage.] 
# show_downloads: ["false"]
google_analytics: ["UA-154946251-1"]

github:
  is_project_page: false